---
title: "MCMC convergence plot"
author: "Yi Huang"
date: "2023-04-30"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.align = "center")
```


\newpage
```{r}
library(dplyr)
library(tidyverse)
```


```{r}
##### Plot for 5000 iterations
plot_df=readRDS("data/new_gibb5000_zn.rds")

testB = plot_df$B[[5000]]
testmu = plot_df$mu[[5000]]
testsigmasq = plot_df$sigmasq[[5000]]
testSIGMA = plot_df$SIGMA[[5000]]
testgamma=plot_df$gamma[[5000]]

```


## Beta plot
```{R}
beta.res.plot <- NULL
for (i in 1:5000) {
  B.res = plot_df$B[[i]]
  B.res = as.data.frame(B.res)
  B.res = rowMeans(B.res, na.rm = T)
  beta.res.plot = rbind(beta.res.plot, B.res)
}

mu.res.plot = NULL
for (i in 1:5000) {
  mu.res = plot_df$mu[[i]]
  mu.res = as.data.frame(t(mu.res))
  mu.res.plot = rbind(mu.res.plot, mu.res)
}
mu.res.plot = NULL

sigma.res.plot = NULL
for (i in 1:5000) {
  sigma.res = plot_df$SIGMA[[i]]
  sigma.res = as.data.frame(sigma.res)
  sigma.res.plot = rbind(sigma.res.plot, sigma.res)
}
```


## beta plot
```{r beta}
par(mfrow = c(3, 5))
plot(beta.res.plot[,1],type = "l", main = bquote("Trace plot of "~ beta[0]), ylab = bquote(beta[0]))
abline(v = 2500, col = 2, lty = 4)
plot(beta.res.plot[,2],type = "l", main = bquote("Trace plot of "~ beta[1]), ylab = bquote(beta[1]))
abline(v = 2500, col = 2, lty = 4)
plot(beta.res.plot[,3],type = "l", main = bquote("Trace plot of "~ beta[2]), ylab = bquote(beta[2]))
abline(v = 2500, col = 2, lty = 4)
plot(beta.res.plot[,4],type = "l", main = bquote("Trace plot of "~ beta[3]), ylab = bquote(beta[3]))
abline(v = 2500, col = 2, lty = 4)
plot(beta.res.plot[,5],type = "l", main = bquote("Trace plot of "~ beta[4]), ylab = bquote(beta[4]))
abline(v = 2500, col = 2, lty = 4)
```


## beta acf

\newpage
## mu plot

```{r}
par(mfrow = c(3, 2))
plot(mu.res.plot[,1],type = "l", main = bquote("Trace plot of "~ mu[0]), ylab = bquote(mu[0]))
plot(mu.res.plot[,2],type = "l", main = bquote("Trace plot of "~ mu[1]), ylab = bquote(mu[1]))
plot(mu.res.plot[,3],type = "l", main = bquote("Trace plot of "~ mu[2]), ylab = bquote(mu[2]))
plot(mu.res.plot[,4],type = "l", main = bquote("Trace plot of "~ mu[3]), ylab = bquote(mu[3]))
plot(mu.res.plot[,5],type = "l", main = bquote("Trace plot of "~ mu[4]), ylab = bquote(mu[4]))
```




\newpage
## sigma^2 plot
```{r}
burn=1
chain_length=5000
#sigmasq
cur_s <- NA
for (i in burn:chain_length) {
  cur_s[i-burn+1] <- plot_df$sigmasq[i]
}

cur_s %>% acf()
cur_s %>% ts.plot(gpars=list(ylab="sigma^2"))
data.frame(cur_s) %>% ggplot(aes(x = cur_s)) + geom_histogram(bins = 50)

plot(sigmasq.res.plot[,1],type = "l", ylim=c(30,40))
```




\newpage
## Sigma_inverse plot
```{r}
Sigma_inv.res.plot = NULL
for (i in 1:5000) {
  Sigma_inv.res = diag(plot_df$SIGMA[[i]])
  Sigma_inv.res = as.data.frame(t(Sigma_inv.res))
  Sigma_inv.res.plot = rbind(Sigma_inv.res.plot, Sigma_inv.res)
}

par(mfrow = c(2, 3))
plot(Sigma_inv.res.plot[,1],type = "l", main = bquote("Trace plot of "~ Sigma[1]), ylab = bquote(Sigma[1]))
abline(v = 2500, col = 2, lty = 4)
plot(Sigma_inv.res.plot[,2],type = "l", main = bquote("Trace plot of "~ Sigma[2]), ylab = bquote(Sigma[2]))
abline(v = 2500, col = 2, lty = 4)
plot(Sigma_inv.res.plot[,3],type = "l", main = bquote("Trace plot of "~ Sigma[3]), ylab = bquote(Sigma[3]))
abline(v = 2500, col = 2, lty = 4)
plot(Sigma_inv.res.plot[,4],type = "l", main = bquote("Trace plot of "~ Sigma[4]), ylab = bquote(Sigma[4]))
abline(v = 2500, col = 2, lty = 4)
plot(Sigma_inv.res.plot[,5],type = "l", main = bquote("Trace plot of "~ Sigma[5]), ylab = bquote(Sigma[5]))
abline(v = 2500, col = 2, lty = 4)
```



\newpage
## Gamma plot

```{r}
gamma.res.plot <- data.frame(matrix(nrow = 14, ncol = 5000))

for (i in 1:5000) {
    gamma.res = plot_df$gamma[[i]]
    gamma.res = as.data.frame(gamma.res)
    gamma.res.plot[,i]=gamma.res
}

gamma.res.plot = t(gamma.res.plot)

par(mfrow=c(3,5))
plot(gamma.res.plot[,1],type = "l",main = bquote("Trace plot of "~ gamma[1]), ylab=bquote(gamma[1]))

plot(gamma.res.plot[,2],type = "l", main = bquote("Trace plot of "~ gamma[2]), ylab=bquote(gamma[2]))

plot(gamma.res.plot[,3],type = "l", main = bquote("Trace plot of "~ gamma[3]), ylab=bquote(gamma[3]))

plot(gamma.res.plot[,4],type = "l", main = bquote("Trace plot of "~ gamma[4]), ylab=bquote(gamma[4]))

plot(gamma.res.plot[,5],type = "l", main = bquote("Trace plot of "~ gamma[5]), ylab = bquote(gamma[5]))
plot(gamma.res.plot[,6],type = "l", main = bquote("Trace plot of "~ gamma[6]), ylab = bquote(gamma[6]))
plot(gamma.res.plot[,7],type = "l", main = bquote("Trace plot of "~ gamma[7]), ylab = bquote(gamma[7]))
plot(gamma.res.plot[,8],type = "l", main = bquote("Trace plot of "~ gamma[8]), ylab = bquote(gamma[8]))

plot(gamma.res.plot[,9],type = "l", main = bquote("Trace plot of "~ gamma[9]), ylab = bquote(gamma[9]))
plot(gamma.res.plot[,10],type = "l", main = bquote("Trace plot of "~ gamma[10]), ylab=bquote(gamma[10]))
plot(gamma.res.plot[,11],type = "l", main = bquote("Trace plot of "~ gamma[11]), ylab=bquote(gamma[11]))
plot(gamma.res.plot[,11],type = "l", main = bquote("Trace plot of "~ gamma[12]), ylab=bquote(gamma[12]))
plot(gamma.res.plot[,13],type = "l", main = bquote("Trace plot of "~ gamma[13]), ylab=bquote(gamma[13]))
plot(gamma.res.plot[,14],type = "l", main = bquote("Trace plot of "~ gamma[14]), ylab=bquote(gamma[14]))
```
















# new plot

```{r}
plot_df=readRDS("data/new_gibb5000_zn.rds")

testB = plot_df$B[[5000]]
testmu = plot_df$mu[[5000]]
testsigmasq = plot_df$sigmasq[[5000]]
testSIGMA = plot_df$SIGMA[[5000]]
testgamma=plot_df$gamma[[5000]]
```

```{r plots}
beta.res.plot = NULL
for (i in 1:5000) {
  B.res = plot_df$B[[i]]
  B.res = as.data.frame(B.res)
  B.res = rowMeans(B.res, na.rm = T)
  beta.res.plot = rbind(beta.res.plot, B.res)
}


mu.res.plot = NULL

for (i in 1:5000) {
  mu.res = plot_df$mu[[i]]
  mu.res = as.data.frame(t(mu.res))
  mu.res.plot = rbind(mu.res.plot, mu.res)
} 


sigma.res.plot = NULL
for (i in 1:5000) {
  sigma.res = plot_df$SIGMA[[i]]
  sigma.res = as.data.frame(sigma.res)
  sigma.res.plot = rbind(sigma.res.plot, sigma.res)
}

gamma.res.plot <- data.frame(matrix(nrow = 14, ncol = 5000))

for (i in 1:5000) {
  gamma.res = plot_df$gamma[[i]]
  gamma.res = as.data.frame(gamma.res)
  gamma.res.plot[,i]=gamma.res
}

gamma.res.plot = t(gamma.res.plot)


sigmasq.res.plot = NULL
for (i in 1:5000) {
  sigmasq.res = plot_df$sigmasq[[i]]
  sigmasq.res = as.data.frame(sigmasq.res)
  sigmasq.res.plot = rbind(sigmasq.res.plot, sigmasq.res)
}

```


```{r beta}
par(mfrow = c(2, 5))

acf_beta0 = acf(beta.res.plot[,1], lag.max = 500)
acf_beta1 = acf(beta.res.plot[,2], lag.max = 500)
acf_beta2 = acf(beta.res.plot[,3], lag.max = 500)
acf_beta3 = acf(beta.res.plot[,4], lag.max = 500)
acf_beta4 = acf(beta.res.plot[,5], lag.max = 500)

plot(acf_beta0, main = bquote(beta[0]))
plot(acf_beta1, main = bquote(beta[1]))
plot(acf_beta2, main = bquote(beta[2]))
plot(acf_beta3, main = bquote(beta[3]))
plot(acf_beta4, main = bquote(beta[4]))

plot(beta.res.plot[,1],type = "l", xlab = "iteration", main = bquote("Trace plot of "~ beta[0]), ylab = bquote(beta[0]))

abline(v = 2500, col = 2, lty = 4)
plot(beta.res.plot[,2],type = "l", xlab = "iteration", main = bquote("Trace plot of "~ beta[1]), ylab = bquote(beta[1]))
abline(v = 2500, col = 2, lty = 4)

plot(beta.res.plot[,3],type = "l", xlab = "iteration", main = bquote("Trace plot of "~ beta[2]), ylab = bquote(beta[2]))
abline(v = 2500, col = 2, lty = 4)

plot(beta.res.plot[,4],type = "l", xlab = "iteration", main = bquote("Trace plot of "~ beta[3]), ylab = bquote(beta[3]))
abline(v = 2500, col = 2, lty = 4)

plot(beta.res.plot[,5],type = "l", xlab = "iteration", main = bquote("Trace plot of "~ beta[4]), ylab = bquote(beta[4]))
abline(v = 1500, col = 2, lty = 4)

hist(unlist(bquote(beta[0])), main = "", breaks = 30, xlab = expression(beta[0]))
hist(unlist(bquote(beta[1])), main = "", breaks = 30, xlab = expression(beta[1]))
hist(unlist(bquote(beta[2])), main = "", breaks = 25, xlab = expression(beta[2]))
hist(unlist(bquote(beta[3])), main = "", breaks = 25, xlab = expression(beta[3]))
hist(unlist(bquote(beta[4])), main = "", breaks = 30, xlab = expression(beta[4]))
```

```{r sigmasq}
burn=1
chain_length=5000
#sigmasq
cur_s <- NA
for (i in burn:chain_length) {
  cur_s[i-burn+1] <- plot_df$sigmasq[i]
}

par(mfrow = c(2, 2))
cur_s %>% acf()
cur_s %>% ts.plot()
data.frame(cur_s) %>% ggplot(aes(x = cur_s)) + geom_histogram(bins = 50)

plot(sigmasq.res.plot[,1],type = "l", ylim=c(30,40))

```


```{r mu}
par(mfrow = c(3, 2))
plot(mu.res.plot[,1],type = "l", main = bquote("Trace plot of "~ mu[0]), ylab = bquote(mu[0]))
plot(mu.res.plot[,2],type = "l", main = bquote("Trace plot of "~ mu[1]), ylab = bquote(mu[1]))
plot(mu.res.plot[,3],type = "l", main = bquote("Trace plot of "~ mu[2]), ylab = bquote(mu[2]))
plot(mu.res.plot[,4],type = "l", main = bquote("Trace plot of "~ mu[3]), ylab = bquote(mu[3]))
plot(mu.res.plot[,5],type = "l", main = bquote("Trace plot of "~ mu[4]), ylab = bquote(mu[4]))
# graphics.off()
```


```{r gamma}
par(mfrow=c(3,5))
plot(gamma.res.plot[,1],type = "l",main = bquote("Trace plot of "~ gamma[1]), ylab=bquote(gamma[1]))

plot(gamma.res.plot[,2],type = "l", main = bquote("Trace plot of "~ gamma[2]), ylab=bquote(gamma[2]))

plot(gamma.res.plot[,3],type = "l", main = bquote("Trace plot of "~ gamma[3]), ylab=bquote(gamma[3]))

plot(gamma.res.plot[,4],type = "l", main = bquote("Trace plot of "~ gamma[4]), ylab=bquote(gamma[4]))

plot(gamma.res.plot[,5],type = "l", main = bquote("Trace plot of "~ gamma[5]), ylab = bquote(gamma[5]))

plot(gamma.res.plot[,6],type = "l", main = bquote("Trace plot of "~ gamma[6]), ylab = bquote(gamma[6]))

plot(gamma.res.plot[,7],type = "l", main = bquote("Trace plot of "~ gamma[7]), ylab = bquote(gamma[7]))

plot(gamma.res.plot[,8],type = "l", main = bquote("Trace plot of "~ gamma[8]), ylab = bquote(gamma[8]))

plot(gamma.res.plot[,9],type = "l", main = bquote("Trace plot of "~ gamma[9]), ylab = bquote(gamma[9]))

plot(gamma.res.plot[,10],type = "l", main = bquote("Trace plot of "~ gamma[10]), ylab=bquote(gamma[10]))

plot(gamma.res.plot[,11],type = "l", main = bquote("Trace plot of "~ gamma[11]), ylab=bquote(gamma[11]))

plot(gamma.res.plot[,11],type = "l", main = bquote("Trace plot of "~ gamma[12]), ylab=bquote(gamma[12]))

plot(gamma.res.plot[,13],type = "l", main = bquote("Trace plot of "~ gamma[13]), ylab=bquote(gamma[13]))

plot(gamma.res.plot[,14],type = "l", main = bquote("Trace plot of "~ gamma[14]), ylab=bquote(gamma[14]))
graphics.off()
```

```{r}
chain_length = 5000
split_res <- list()
cur_start <- 1
nsplits <- 5
nchain <- chain_length
for (i in 1:nsplits) {
  cur_end <- i*nchain/nsplits
  split_res[[i]] <- list(plot_df$B[cur_start:cur_end], 
                         plot_df$mu[cur_start:cur_end], 
                         plot_df$sigmasq[cur_start:cur_end], 
                         plot_df$SIGMA[cur_start:cur_end],
                         plot_df$gamma[cur_start:cur_end])
  cur_start <- cur_start + (nchain/nsplits)
}

res1 <- split_res[[1]]
res2 <- split_res[[2]]
res3 <- split_res[[3]]
res4 <- split_res[[4]]
res5 <- split_res[[5]]


B_list <- c(res1[[1]], 
            res2[[1]], 
            res3[[1]], 
            res4[[1]], 
            res5[[1]])

mu_list <- c(res1[[2]], 
             res2[[2]], 
             res3[[2]], 
             res4[[2]], 
             res5[[2]])

sigmasq_list <- c(res1[[3]], 
                  res2[[3]], 
                  res3[[3]], 
                  res4[[3]], 
                  res5[[3]])

big_sigma_list <- c(res1[[4]], 
                    res2[[4]], 
                    res3[[4]], 
                    res4[[4]], 
                    res5[[4]])

es_list <- list( B = B_list,
                 mu = mu_list, 
                 sigmasq = sigmasq_list, 
                 big_sigma = big_sigma_list)

## pick a hurricane GEORGE.1951

burn = 0
cur_B = data.frame()
res = es_list
for (i in 1:5) {
  for (j in (burn+1):5000) {
    cur_B[j,i] = res$B[[j]][i,20]
  }
}
colnames(cur_B) = paste0("beta", 0:4)


par(mfrow = c(3,5))
acf(cur_B[1])
acf(cur_B[2])
acf(cur_B[3])
acf(cur_B[4])
acf(cur_B[5])

ts.plot(cur_B[1], xlab = "iteration", ylab = expression(beta[0]))
ts.plot(cur_B[2], xlab = "iteration", ylab = expression(beta[1]))
ts.plot(cur_B[3], xlab = "iteration", ylab = expression(beta[2]))
ts.plot(cur_B[4], xlab = "iteration", ylab = expression(beta[3]))
ts.plot(cur_B[5], xlab = "iteration", ylab = expression(beta[4]))

hist(unlist(cur_B[1]), main = "", breaks = 30, xlab = expression(beta[0]))
hist(unlist(cur_B[2]), main = "", breaks = 30, xlab = expression(beta[1]))
hist(unlist(cur_B[3]), main = "", breaks = 25, xlab = expression(beta[2]))
hist(unlist(cur_B[4]), main = "", breaks = 25, xlab = expression(beta[3]))
hist(unlist(cur_B[5]), main = "", breaks = 30, xlab = expression(beta[4]))

graphics.off()
```




\newpage
# Appendix: code
```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
```